### ISSUE TITLE
Not able to deserealise with latest GSON and this library

### ISSUE THREAD

**Issue by CyborTronik** [gkopff/gson-jodatime-serialisers#33]
I'm getting:
```
java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
	at com.fatboyindustrial.gsonjodatime.DateTimeConverter.deserialize(DateTimeConverter.java:85)
	at com.fatboyindustrial.gsonjodatime.DateTimeConverter.deserialize(DateTimeConverter.java:44)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.Gson.fromJson(Gson.java:814)
	at com.google.gson.Gson.fromJson(Gson.java:779)
	at com.google.gson.Gson.fromJson(Gson.java:728)
	at com.google.gson.Gson.fromJson(Gson.java:700)
```
For object with next fields:
```
private String id;
    private DateTime createdAt;
    private DateTime updatedAt;
    private boolean enabled;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public DateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(DateTime createdAt) {
        this.createdAt = createdAt;
    }

    public DateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(DateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
```
Using:
```

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.4</version>
        </dependency>
        <dependency>
            <groupId>com.fatboyindustrial.gson-jodatime-serialisers</groupId>
            <artifactId>gson-jodatime-serialisers</artifactId>
            <version>1.2.0</version>
        </dependency>
```

**Comment by gkopff** [comment]
@CyborTronik do you know if this example works okay using GSON 2.3.1?
